version: '3.7'

services:
  currency-exchange:
    image: josecho/mmv2-currency-exchange-service-v2:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    networks: 
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

  naming-server:
    image: josecho/mmv2-naming-server-v2:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks: 
      - currency-network
  currency-conversion:
    image: josecho/mmv2-currency-conversion-service-v2:0.0.1-SNAPSHOT
    ports:
      - "8100:8100"
    networks: 
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      
networks:
  currency-network: 
    

